workflows:
  android-release-pipeline:
    name: ShiftDrop Android Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Fresh Recreate and Build APK
        script: |
          # පරණ නෑටිව් ෆෝල්ඩරය ඉවත් කර v2 ප්‍රමිතියෙන් අලුතින් සැකසීම
          rm -rf android/
          flutter create . --platforms=android
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
